# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c3e6b19766865cd4c1b1eb71be60d93c1f2cdf6ba63d12e70c9ac2c9e8b9390b3a4c13fcfc3087d7f916f1d8ab9b7f75948c0663ce7ffd651c9b65376010861

test:
  secret_key_base: 10b51a0b9acb1427248b3622eea38aad3bec7a8d5394223935e38591dfc1a4b6aeb21f689fc4db209206327aaa2c2e59312de39634867a63316eca4396b6ae01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
